### ISSUE TITLE
Plinko Probability master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/plinko-probability#12]
## Design
- [x] **Design doc created** (Date: 06/23/2014) 
 - [x] Make phethelp@gmail.com owner, share with phet-team
 - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 07/07/2014)
- [x] **Design concept complete**  (Date: 07/09/2014)
- [x] **Wireframes complete** (Date: 07/17/2014) 
- [x] **Mockups complete** (Date: 12/12/2014) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 06/22/2016) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 9/15/16) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Compatible activities ([author spreadsheet] (https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [x] Update [Gooru spreadsheet] (https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [ ] Sim primer
  - [x] Verify credits
- [x] **Add to Edmodo**

## Implementation
- [x] **Sim repo created** (Date: 06/13/2014) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme file
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Unfuddle tickets reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo (auto-ported strings from Java and Flash sims can
  be found in babel/autoport). The strings should be deleted from babel/autoport and @jbphet should immediately be asked
  to pull from rosetta to avoid conflicts.
- [x] **Initial development started** (Date: 11/25/2014)
- [x] **Sim feature complete** (Date: 05/31/2016) 
- [x] **Code review complete** (Date: 07/01/2016) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 9/29/16)
  - [x] Update repo README to published template

## QA
- [x] **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing complete** (Date: 9/16/16) 
- [x] **First release candidate** (Date: 9/16/16)
 - [x] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
 - [x] Test matrix deemed complete

**Comment by ariel-phet** [comment]
@amanda-phet can you check off the current relevant items here (lead designer sign off mainly, and probably good for you to review ?showPointerAreas)

@pixelzoom is finishing off this sim and will likely move quickly so would be good to get our docs in a row

**Comment by ariel-phet** [comment]
And please assign back to me after those steps @amanda-phet

**Comment by pixelzoom** [comment]
@ariel-phet @amanda-phet 1.0.0 is published. Assigning this to you to complete the remaining checklist items.

**Comment by ariel-phet** [comment]
@amanda-phet I am all done here, looks like the sim primer is really the only thing remaining (unless an activity or two can shift over)

**Comment by amanda-phet** [comment]
Always the sim primer... can we remove that from the master checklist? It's unlikely that a primer will be ready close to a sim's publication date, and it would be nice to be able to close this issue.

**Comment by pixelzoom** [comment]
You can always break out uncompleted items into separate issues, then close this issue.

**Comment by ariel-phet** [comment]
@amanda-phet  I think @pixelzoom makes a good point. I don't really want to remove it from the checklist, since this is supposed to be a true list of everything the needs to be done associated with the sim. I will make an issue for the sim primer and close this one.

**Comment by ariel-phet** [comment]
Primer issue here: https://github.com/phetsims/plinko-probability/issues/98

Closing
